apiVersion: apps/v1
kind: Deployment
metadata:
  name: ojala-apigateway
  namespace: demo
  labels:
    app: ojala-apigateway
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ojala-apigateway
  template:
    metadata:
      labels:
        app: ojala-apigateway
        component: backend
    spec:
      containers:
      - name: ojala-apigateway
        image: ojala/apigateway:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Staging"
        - name: ASPNETCORE_URLS
          value: "http://+:5001"
        livenessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5001
          initialDelaySeconds: 15
          periodSeconds: 5
