apiVersion: apps/v1
kind: Deployment
metadata:
  name: ojala-patient-app
  namespace: demo
  labels:
    app: ojala-patient-app
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ojala-patient-app
  template:
    metadata:
      labels:
        app: ojala-patient-app
        component: frontend
    spec:
      containers:
      - name: ojala-patient-app
        image: ojala/patient-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_URL
          value: "http://ojala-apigateway.demo.svc.cluster.local"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
