groups:
  - name: OjalaHealthcarePlatform
    rules:
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% for the last 5 minutes"

      - alert: HighLatency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service)) > 0.5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected"
          description: "95th percentile of request duration is above 500ms for service {{ $labels.service }}"

      - alert: ApiGatewayDown
        expr: up{job="api-gateway"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "API Gateway is down"
          description: "API Gateway has been down for more than 1 minute"

      - alert: LegacyApiDown
        expr: up{job="legacy-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Legacy API is down"
          description: "Legacy API has been down for more than 1 minute"

      - alert: OjalaApiDown
        expr: up{job="ojala-api"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Ojala API is down"
          description: "Ojala API has been down for more than 1 minute"

      - alert: AiEngineDown
        expr: up{job="ai-integration"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "AI Engine is down"
          description: "AI Engine has been down for more than 1 minute"

      - alert: HighCPUUsage
        expr: avg by(instance) (rate(node_cpu_seconds_total{mode!="idle"}[5m])) > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is above 80% for instance {{ $labels.instance }} for the last 5 minutes"

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes > 0.9
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is above 90% for instance {{ $labels.instance }} for the last 5 minutes"

      - alert: HighDiskUsage
        expr: node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"} < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is above 90% for instance {{ $labels.instance }} for the last 5 minutes"
