services:
  # Vault Server (for local development)
  vault:
    image: hashicorp/vault:1.15.2
    container_name: ojala-vault
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    command: vault server -dev -dev-root-token-id=root
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ojala-network

  # Vault Agent for Ojala API
  vault-agent-ojala-api:
    build:
      context: ./vault
      dockerfile: Dockerfile
    container_name: ojala-vault-agent-api
    depends_on:
      vault:
        condition: service_healthy
    environment:
      - VAULT_ADDR=http://vault:8200
    volumes:
      - ojala-secrets:/vault/secrets
      - ./vault/role-id:/vault/config/role-id:ro
      - ./vault/secret-id:/vault/config/secret-id:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "test", "-f", "/vault/secrets/jwt-secret.json"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - ojala-network

  # Ojala API with Vault integration
  ojala-api:
    build:
      context: .
      dockerfile: src/backend/Ojala.Api/Dockerfile
    container_name: ojala-api
    ports:
      - "5000:80"
    depends_on:
      vault-agent-ojala-api:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    volumes:
      - ojala-secrets:/vault/secrets:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ojala-network
    command: >
      sh -c "
        echo 'Waiting for JWT secret file...' &&
        while [ ! -f /vault/secrets/jwt-secret.json ]; do
          sleep 2;
        done &&
        echo 'JWT secret file found, starting application...' &&
        dotnet Ojala.Api.dll
      "

volumes:
  ojala-secrets:
    driver: local

networks:
  ojala-network:
    driver: bridge
