# Default values for nurse-assistant chart - Production Environment
# This is a YAML-formatted file.

replicaCount: 3

image:
  repository: registry.hub.docker.com/your-org/ojala-nurse-assistant
  tag: stable
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""

rbac:
  create: true
  extraRules: []

podSecurityContext:
  fsGroup: 1000

securityContext:
  runAsUser: 1000
  runAsNonRoot: true
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
  hosts:
    - host: nurse-assistant.ojala.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: nurse-assistant-prod-tls
      hosts:
        - nurse-assistant.ojala.com

resources:
  limits:
    cpu: 2000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

nodeSelector:
  node-type: production

tolerations:
  - key: "workload-type"
    operator: "Equal"
    value: "production"
    effect: "NoSchedule"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - nurse-assistant
      topologyKey: kubernetes.io/hostname
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - nurse-assistant
        topologyKey: topology.kubernetes.io/zone

vault:
  enabled: true
  addr: "http://vault.production:8200"
  token: "ojala-prod-token"

serviceMonitor:
  enabled: true
  interval: "10s"
  scrapeTimeout: "5s"
  labels:
    release: prometheus
