apiVersion: apps/v1
kind: Deployment
metadata:
  name: ojala-identity
  namespace: demo
  labels:
    app: ojala-identity
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ojala-identity
  template:
    metadata:
      labels:
        app: ojala-identity
        component: backend
    spec:
      containers:
      - name: ojala-identity
        image: yourdockerhubuser/ojala-identity:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: ojala-identity-config
        - secretRef:
            name: ojala-identity-secrets
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Staging"
        - name: ASPNETCORE_URLS
          value: "http://+:5000"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5 