apiVersion: v1
kind: Service
metadata:
  name: ojala-identity
  namespace: demo
  labels:
    app: ojala-identity
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: ojala-identity 