apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ojala-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/ojala-healthcare-platform.git
    targetRevision: HEAD
    path: charts
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true
    # No automated sync for production - requires manual approval
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: autoscaling
      kind: HorizontalPodAutoscaler
      jsonPointers:
        - /spec/metrics
