apiVersion: apps/v1
kind: Deployment
metadata:
  name: ojala-redis-deployment
  namespace: ojala-ns
  labels:
    app: ojala-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ojala-redis
  template:
    metadata:
      labels:
        app: ojala-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            exec:
              command:
                - redis-cli
                - ping
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: ojala-redis-service
  namespace: ojala-ns
  labels:
    app: ojala-redis
spec:
  type: ClusterIP
  selector:
    app: ojala-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
