apiVersion: v1
kind: Service
metadata:
  name: ojala-patient-app
  namespace: demo
  labels:
    app: ojala-patient-app
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ojala-patient-app
