apiVersion: v1
kind: Service
metadata:
  name: ojala-ai-engine
  namespace: demo
  labels:
    app: ojala-ai-engine
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ojala-ai-engine
