apiVersion: v1
kind: Service
metadata:
  name: ojala-patientportal
  namespace: demo
  labels:
    app: ojala-patientportal
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: ojala-patientportal
