name: Terraform Plan & Validate

on:
  push:
    branches: [ ci-workflows ]
  pull_request:
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Terraform Init
        run: terraform init
        working-directory: infra/terraform
      
      - name: Terraform Validate
        run: terraform validate
        working-directory: infra/terraform
      
      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: infra/terraform
      
      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: infra/terraform/tfplan 

  terraform-apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform
    if: github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Init
        run: terraform init
        working-directory: infra/terraform
      
      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: infra/terraform 